export const data = [
	{
		id: 1,
		product_img: './img/canelones.jpg',
		product_name: 'Sorrentinos',
		product_description: 'Canelones de verduras y ricota',
		product_price: 2500,
		quantity: 1,
	},
	{
		id: 2,
		product_img: './img/Sorrentinos.jpg',
		product_name: 'Sorrentinos',
		product_description: 'Sorrentinos de calabaza con salsa blanca',
		product_price: 2500,
		quantity: 1,
	},
	{
		id: 3,
		product_img: './img/ravioles.jpg',
		product_name: 'Revioles',
		product_description: 'Ravioles de carne y verduras con Tuco',
		product_price: 2300,
		quantity: 1,
	},
	{
		id: 4,
		product_img: './img/tallarines.jpg',
		product_name: 'Tallarines',
		product_description: 'Tallarines con salsa bolognesa',
		product_price: 2300,
		quantity: 1,
	},
	{
		id: 5,
		product_img: './img/milanesas_pure.jpg',
		product_name: 'Milanesas con Pure',
		product_description: 'Milanesa de ternera con pure de papas',
		product_price: 2500,
		quantity: 1,
	},
	{
		id: 6,
		product_img: './img/humita.jpg',
		product_name: 'Humita',
		product_description: 'Humita con queso',
		product_price: 2000,
		quantity: 1,
	},
	{
		id: 7,
		product_img: './img/locro.jpg',
		product_name: 'Locro',
		product_description: 'Locro con carne y legumbres',
		product_price: 2300,
		quantity: 1,
	},
	{
		id: 7,
		product_img: './img/lasaña.jpg',
		product_name: 'Lasaña',
		product_description: 'Lasaña de Carne y Verduras',
		product_price: 2000,
		quantity: 1,
	},
	
	// Aquí pueden agregar más o modificar los productos existentes
];
